# Site settings
title: Tablk blog
email:
description: > # this means to ignore newlines until "baseurl:"
  Tablkの使いかたなどを説明するブログです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tablk.net" # the base hostname & protocol for your site
twitter_username: Tablk_Official

# Build settings
markdown: kramdown

gems:
  - jekyll-archives

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
