# Site settings
title: Tablk
email:
description: >
  ユーザー登録するだけで、PCでも、スマホのブラウザでも楽しめる。<br>
  テーブルトークRPG向けのチャットツールです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tablk.net" # the base hostname & protocol for your site
twitter_username: Tablk_Official

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
